export const APPLICATION_ERROR_CODES = {
  NOT_AUTHENTICATED: 'NOT_AUTHENTICATED',
  ACCESS_DENIED: 'ACCESS_DENIED',
  TERMS_NOT_ACCEPTED: 'TERMS_NOT_ACCEPTED',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  CONCURRENCY_CONFLICT: 'CONCURRENCY_CONFLICT',
  INVALID_STATE: 'INVALID_STATE',
} as const;

export type ApplicationErrorCode =
  typeof APPLICATION_ERROR_CODES[keyof typeof APPLICATION_ERROR_CODES];
